[env]
_.python.venv = { path = "{{config_root}}/.venv", create = true }
KUBECONFIG = "{{config_root}}/kubeconfig"
MINIJINJA_CONFIG_FILE = "{{config_root}}/.minijinja.toml"
SOPS_AGE_KEY_FILE = "{{config_root}}/age.key"
TALOSCONFIG = "{{config_root}}/talosconfig"

[tools]
"python" = "3.14.3"
"aqua:cilium/cilium-cli" = "0.19.1"
"aqua:cli/cli" = "2.87.0"
"aqua:cloudflare/cloudflared" = "2026.2.0"
"aqua:FiloSottile/age" = "1.3.1"
"aqua:fluxcd/flux2" = "2.7.5"
"aqua:getsops/sops" = "3.12.0"
"aqua:go-task/task" = "3.48.0"
"aqua:helm/helm" = "3.20.0"
"aqua:helmfile/helmfile" = "1.3.0"
"aqua:jqlang/jq" = "1.8.1"
"aqua:kubernetes-sigs/kustomize" = "5.7.1"
"aqua:kubernetes/kubernetes/kubectl" = "1.35.1"
"aqua:mikefarah/yq" = "4.52.4"
"aqua:siderolabs/talos" = "1.12.4"
"aqua:yannh/kubeconform" = "0.7.0"
"rust" = "1.93.1"
"cargo:minijinja-cli" = "2.12.0"
